### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [janellias/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by janellias** [comment]
Figured it out :) Just had to add the meta viewport tag between <head></head> in application.html.erb.  Also learned how to test for different devices in Chrome, which should help me avoid these issues in the future.

**Comment by kenmazaika** [comment]
Looks perfect.  That's exactly right. :+1:
